### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Pavliistanislav** [Pavliistanislav/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by pavliistas** [comment]
<h1 class = "name">DONALD TRUMP</h1>
<ul class="contacts">
<li>
<a href ="https://www.fb.com/DonaldTrump" rel="author" class = "facebook">
<span>Donald Trump</span>
</a>
</li>

<li>
<a href="mailto:realDonaldTrump@whitehouse.gov" rel="author" class = "mail">
 <span>realDonaldTrump@whitehouse.gov</span>
</a>
</li>

<li>
<a href="https://twitter.com/realDonaldTrump" rel="author" class = "twitter">
 <span>realDonaldTrump</span>
</a>
</li>

<li>
<a href=" https://www.instagram.com/realDonaldTrump/" rel="author" class = "instagram">
 <span>realDonaldTrump</span>
</a>
</li>
